CREATE TABLE Endpoints (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(100) NOT NULL,
    Url NVARCHAR(500) NOT NULL,
    CheckIntervalSeconds INT NOT NULL DEFAULT 60,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);

CREATE TABLE ExecutionLogs (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    EndpointId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Endpoints(Id) ON DELETE CASCADE,
    StatusCode INT NULL,
    ResponseTimeMs INT NOT NULL,
    IsSuccess BIT NOT NULL,
    ErrorMessage NVARCHAR(MAX) NULL,
    CheckedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);

CREATE INDEX IX_ExecutionLogs_EndpointId_CheckedAt
ON ExecutionLogs (EndpointId, CheckedAt DESC)
INCLUDE (ResponseTimeMs, IsSuccess);